### ISSUE TITLE
Do not call batchprocessor with empty list

### ISSUE THREAD

**Issue by kascakm** [rovats/java-utils#9]
If the stream size is a multiple of the batch size (e.g. stream size = 20, batch size = 10), the finishers calls the batchProcessor with empty list. I'm thinking this may not be necessary? (it's actually causing issue with my batchprocessor as it does not expect empty list)

Adding the empty check may help, but I'm not sure there are other implications of this.
```
public Function<List<T>, List<T>> finisher() {
        return ts -> {
            if (!ts.isEmpty()) { 
                batchProcessor.accept(ts);
                recordsProcessed += ts.size();
            }
            return Collections.emptyList();
        };
    }
```

Thanks
Michal

**Comment by rovats** [comment]
Fixed, thanks for raising this!
